(define (make-interval x y) (cons x y))

(define (lower-bound x) (min (car x) (cdr x)))
(define (upper-bound x) (max (cdr x) (cdr x)))

(define (mul-interval x y)
    (let ((p1 (* (lower-bound x) (lower-bound y)))
          (p2 (* (lower-bound x) (upper-bound y)))
          (p3 (* (upper-bound x) (lower-bound y)))
          (p4 (* (upper-bound x) (upper-bound y))))
        (make-interval (min p1 p2 p3 p4) 
                       (max p1 p2 p3 p4))))

(define (new-mul-interval x y)
    (cond ((And (> (lower-bound x) 0)  
                (> (lower-bound y) 0))  
                    (make-interval (* (lower-bound x) (lower-bound y)) 
                                   (* (upper-bound x) (upper-bound y))))
          ((And (< (upper-bound x) 0) 
                (< (upper-bound y) 0))
                    (make-interval (* (lower-bound x) (lower-bound y)) 
                                   (* (upper-bound x) (upper-bound y))))
          ((And (< (lower-bound x) 0)
                (> (lower-bound y) 0))  
                    (make-interval (* (lower-bound x) (upper-bound y))
                                   (* (lower-bound y) (upper-bound x))))
          ((And (> (lower-bound x) 0)
                (< (lower-bound y) 0))
                    (make-interval (* (lower-bound y) (upper-bound x))
                                   (* (upper-bound x) (upper-bound y))))
          (()) ; ... TODO:
          ))


(display (mul-interval (make-interval 3 5) (make-interval -5 6)))
(newline)
(display (new-mul-interval (make-interval 3 5) (make-interval -5 6)))
